### PR TITLE
Make all notifications public on Lollipop

### PR DESCRIPTION
**Pull request by cco3**
I'm aware that it's requested to file an issue first before creating a commit.  This change was mostly just so I could play with the code so I didn't bother creating an issue.

This was tested on a Nexus 5 running Android 5.1

### CODE REVIEW

**Comment by g-ortuno** [comment]
Could you explain what's the purpose of this change?

**Comment by cco3** [comment]
Sorry, I'll put that in the review message next time.  As the commit message says:
"""
There doesn't seem to be any reason why public beacons would give
anything other than public notifications.  This change makes beacons
publicly visible on the Android 5.0 lock screen.
"""

**Comment by g-ortuno** [comment]
The only time where the contents of the notification will be hidden is if the user explicitly sets "Hide Sensitive Information". If that's the case I don't see why we should force the notification to be public when the user clearly wants privacy.

**Comment by cco3** [comment]
"hide sensitive information" is for hiding things like personal information.  If this wasn't meant to be overridden by notifications that consider themselves public, such functionality wouldn't be allowed by the platform.  If the user *really* wants that level of privacy, that's what the "don't show notifications at all" option is for.

http://developer.android.com/about/versions/android-5.0-changes.html
"If the notification does not contain personal information, or if you want to allow media playback control on the notification, call the setVisibility() method and set the notification's visibility level to VISIBILITY_PUBLIC."

**Comment by cco3** [comment]
An example from the gmail app: with "hide sensitive information" on, single email notifications won't show any content because the subject of the email is personal and sensitive.  However, when you get a notification for multiple emails, the notification shows as it normally would, telling you how many emails you have waiting, because the number of emails isn't that personal.

**Comment by g-ortuno** [comment]
1. But the app could potentially show personal information. The Physical
Web supports other protocols like mDNS where you have to be connected to
the same WiFi network as the device which mean some of the devices are
meant to be private. I can imagine a case where someone has a private
device in their network that wouldn't want to expose in his/her lock
screen.

2. That's a different case. If you want to expose the number of devices
around I have no problem but you are exposing potentially private
information about these devices.

**Comment by cco3** [comment]
OK, if not all beacons are public, that negates the premise of the commit message.

filed #300.

**Comment by cco3** [comment]
OK, taking another shot at this.  I'm leaving all urls discovered through mdns and ssdp as private.

**Comment by cco3** [comment]
But apparently I need an admin to reopen this for me?  Anyway, I've updated the branch.

**Comment by dinhviethoa** [comment]
I'm unable to re-open the pull request as well...

**Pull request closed without merging**
