### PR TITLE
support URL in WiFi SSID - Android

### PR DESCRIPTION
**Pull request by jonasevcik**
Added support for scanning surrounding WiFi APs. URLs discovered in SSIDs are reported to PwoDiscoveryService.

### CODE REVIEW

**Comment by scottjenson** [comment]
@jonasevcik Happy to discuss this with you. Our Android dev is out this week but will get back to you next week. Didn't want you to think we'd forgotten you.

Scott

**Comment by jonasevcik** [comment]
@scottjenson OK, no problem.

**Comment by scottjenson** [comment]
Please see my comment to issue #477. We very much appreciate the effort but don't feel it's useful to support two different wifi approaches. We are going to stick with just mDNS.

**Comment by scottjenson** [comment]
@jonasevcik We discussed this in the issues awhile back. Just finally getting around to commenting. This is a clever idea (the original Physical Web prototype did just this) but it's a bit of a hack on top of wifi and doesn't really buy you much (given how cheap BLE beacons are getting.

**Pull request closed without merging**
