### PR TITLE
[web-service] Add secureOnly options to body request

### PR DESCRIPTION
**Pull request by beaufortfrancois**
R=@mmocny

### CODE REVIEW

**Comment by mmocny** [comment]
Francois, this LGTM.  From the looks of it the HTTPS requirement is only on the final URL which is what we want.  And thanks for some adding tests!

However, I'm off on vacation until after Easter and even if I merge, will not be able to deploy.

@cco3 and @nondebug feel free to merge.

**Comment by oahziur** [comment]
I might be able to help deploy this if necessary. I think I have the access to both `url-caster-dev` and `url-caster` App Engine project. Otherwise, we can wait after Easter.

**Comment by beaufortfrancois** [comment]
Please let me know when it's live.

**Comment by oahziur** [comment]
@beaufortfrancois Both `url-caster` and `url-caster-dev` are up to date.

**Comment by beaufortfrancois** [comment]
Thank you!

**Pull request merged**
