### PR TITLE
[PWS] Start/stop auto test server more reliably

### PR DESCRIPTION
**Pull request by cco3**
This makes the tests a little more reliable, but I'm still not sure how to reliably reproduce #365

### CODE REVIEW

**Comment by mmocny** [comment]
When I try to run this, I always get "Rogue server is already running", even though I can bind port fine without this patch.

**Comment by cco3** [comment]
ps -ef | grep dev_appserver

Is there anything there?

**Comment by mmocny** [comment]
There was, killing it resolves the issue, thanks.

Curious though why it would ignore the bind issue in the other case?

**Comment by cco3** [comment]
Yea...that confuses me...I didn't change the port number.

**Pull request merged**
