### PR TITLE
[PWS] Fixed encoding on title and description metadata

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Go to http://url-caster-fr.appspot.com/webui and enter "http://www.blackanddecker.fr/".
Before:
```
{
  "metadata": [
    {
      "description": "BLACK+DECKERâ¢ est le premier fournisseur mondial d'outils Ã©lectriques et d'accessoires.",
      "url": "http://www.blackanddecker.fr/",
      "rank": 1000,
      "icon": "http://www.blackanddecker.fr/favicon.ico",
      "title": "Outils Ã©lectriques & Outils de jardin â BLACK+DECKERâ¢",
      "id": "http://www.blackanddecker.fr/"
    }
  ]
}
```
After:
```
{
  "metadata": [
    {
      "description": "BLACK+DECKER™ est le premier fournisseur mondial d'outils électriques et d'accessoires.",
      "url": "http://www.blackanddecker.fr/",
      "rank": 1000,
      "icon": "http://www.blackanddecker.fr/favicon.ico",
      "title": "Outils électriques & Outils de jardin – BLACK+DECKER™",
      "id": "http://www.blackanddecker.fr/"
    }
  ]
}
```

### CODE REVIEW

**Comment by mmocny** [comment]
I had to revert this because resolving `"http://www.google.com"` will fail.  Probably a simple fix, but wanted to revert first.

```
curl -k -s -H "Content-Type: application/json" -d '{"objects":[{"url":"http://www.google.com"}]}' http://localhost:8080/resolve-scan
```

**Comment by mmocny** [comment]
Got:

```
BadValueError: Expected valid UTF-8, got 'Search Images Maps Play YouTube News Gmail Drive More Web History Settings Sign in \xd7 A faster way to browse the web Install Google Chrome Canada \xa0 Advanced search Language tools Fran\xe7ais Advertising\xa0Programs Business Solutions +Google About Google Google.com Privacy Terms'
```

**Comment by beaufortfrancois** [comment]
Hey Michal, I've uploaded another PR that addresses this issue: https://github.com/google/physical-web/pull/389

**Comment by dinhviethoa** [comment]
We probably need unit tests for the encoding issues.

**Comment by dinhviethoa** [comment]
Just to let you know, I tried https://pypi.python.org/pypi/chardet before but it was too slow.

**Comment by dinhviethoa** [comment]
https://github.com/ovalhub/pyicu is faster (using C binding) but might not be available on app engine.

**Pull request merged**
