### PR TITLE
[PWS] Add checkbox to bypass cache at /webui

### PR DESCRIPTION
**Pull request by beaufortfrancois**
When I'm playing with https://url-caster.appspot.com/webui, I'd love it if it would always fetch website instead of returning stale data. It is particularly true with local servers.

### CODE REVIEW

**Comment by mmocny** [comment]
Thats a good point, but then it isn't testing the PWS the same way other clients do.  It could also prevent us seeing bugs.

I usually just use curl if I want to do this:

```
curl --data '{"objects": [{"url":"http://google.ca", "force":true}]}' "http://www.url-caster-dev.appspot.com/resolve-scan"
```

Also, I expect our caching strategy to change over time (like actually respecting cache-control headers)

**Comment by beaufortfrancois** [comment]
Could we add a "force update" checkbox to the UI then?

**Comment by beaufortfrancois** [comment]
What do you think of that? See amended commit.
screenshot 2015-05-07 at 3 27 32 pm

**Comment by mmocny** [comment]
I like it!

**Pull request merged**
