### PR TITLE
[android] Reflect new PWS metadata values

### PR DESCRIPTION
**Pull request by cco3**
This change properly uses the metadata values currently returned by PWS.

* Adds displayUrl
* Adds rank
* Removes score

@mmocny PTAL at PwsClient.java and make sure I'm not expecting any metadata values that aren't guaranteed, etc.

### CODE REVIEW

**Comment by g-ortuno** [comment]
What's the difference between url and displayUrl?

**Comment by cco3** [comment]
displayUrl is a new value returned by the metadata server that is the url that is supposed to be displayed.  I think the idea is that the url to be displayed could be a shortened url or a lengthened url depending on which one is more useful.

**Comment by cco3** [comment]
lost a file...trying to find it...

**Comment by g-ortuno** [comment]
But that's the same as siteUrl...

**Comment by cco3** [comment]
Not necessarily given the description I just gave...displayUrl is a bit more variable.  See #388 for more info.

**Comment by g-ortuno** [comment]
So we now have three urls?
1. id (basically the original URL) used for our map of devices
2. siteUrl used when opening a link
3. displayUrl self explanatory

**Comment by g-ortuno** [comment]
LGTM

**Comment by cco3** [comment]
That's correct.

**Pull request merged**
