### PR TITLE
Added the exceptions on jsons in PhysicalWebCollection

### PR DESCRIPTION
**Pull request by RajPratim21**

### CODE REVIEW

**Comment by RajPratim21** [comment]
During the initial setup src/java files can't find the files in the folder lib: so I also moved pwsCollections from lib/org.pws.collections to app/main/org.physical.web/collections

**Comment by cco3** [comment]
Are you  trying to develop in android studio? We've had trouble getting the library set up correctly in studio.  Just build from the command line, e.g., `adb installDebug`

Anyway, you are going to have to put the library back where it's supposed to be.

**Comment by RajPratim21** [comment]
Yes I was building with android studio

**Comment by RajPratim21** [comment]
I have a query It seems to  works with the libs under the src\main in my system can't it be done like this? I am a novice so I am apologizing for the naive comments though.

**Comment by cco3** [comment]
We have this code separated out into a distinct library so that it can be used by itself.  We don't want to move that library under the directory for the app.

**Comment by cco3** [comment]
Closing due to inactivity.  Please let me know if you wish to pursue this.

**Pull request closed without merging**
