### PR TITLE
Remove IDE project files from repo.

### PR DESCRIPTION
**Pull request by devunwired**
IML files for Android Studio are generated files and should not be checked into source. They are always derived from the `build.gradle` files which represent the source of truth in the project. Their format is subject to variation as different versions of Studio will generate a different XML structure in the files.

This commit removes the checked-in files and adds the type to `.gitignore`.

### CODE REVIEW

**Comment by g-ortuno** [comment]
See #371

**Comment by g-ortuno** [comment]
Do you have a source saying that this files are not useful?

**Comment by devunwired** [comment]
@g-ortuno Certainly, see below…

Comments from an Android Studio tools team developer indicating they are generated content:
https://code.google.com/p/android/issues/detail?id=77983#c7
https://code.google.com/p/android/issues/detail?id=156708#c6

StackOverflow answer form another tools team developer indicating this + the entire `.idea/` directory should not be tracked in a Studio project:
http://stackoverflow.com/a/27570950/246461

…If I can find the Google I/O video where they made the same statement on stage, I'll post it here as well.

**Comment by cco3** [comment]
LGTM.

**Comment by g-ortuno** [comment]
@cco3 beat me to the lgtm

**Pull request merged**
