### PR TITLE
Integrate new library into PW android app

### PR DESCRIPTION
**Pull request by cco3**

### CODE REVIEW

**Comment by cco3** [comment]
So at this point everything is mostly working, but the frame rate is unexpectedly poor.  I've tried setting up strict mode and nothing fires for me.

**Comment by cco3** [comment]
Change updated

**Comment by cco3** [comment]
Updated

**Comment by Thetzleoo** [comment]
Karl and Thomas D Parker Sir. Will no longer not be participating in this project, and has been doing so in Washington State Rocketparticipatingand Sunnyvale Biosphere #3

**Comment by Thetzleoo** [comment]
Karl Rockefeller and Thomas D Parker Sr. Has been and will continue to be participating in this project through , Rocket Man Northrop Gummans and Langley Texas, and can be reached at Karl.Rockefeller@Yahoo.com or 407-308-8375.

**Comment by LadyBird1960** [comment]
Thanks Thomas
Den 2. maj 2016 8.33 PM skrev "Thomas Parker Sr." <notifications@github.com

**Comment by LadyBird1960** [comment]
I will drink cup of Coffee tonight i n peace an in most dispair for money
to my abuseful lost for nicotine content toback tobak expences....
But at the end it endelig ender med én sidste Bill to Pay.
Excactly.  Y quite rigt.
No money to Pay MobilePay.
Therefore next step....
If anybodyes Bill Can't be payed i n common situation.
I decide herefter. :
Can't Pay All.  Therefore noone get payed.
I will have money enough then.
Atleast to ✌ gogo an Bye myself a fresh start of nicotine adoption in the
format of E-smoke/cigaretter /Homeroll tobaco and i even will albue myself
smoke pige with mysterium i n form of matches what a greating of life my
living will be.
To be or not To Be...
No more a quidtion to me ✌...
Den 3. maj 2016 2.43 AM skrev "Lene Hye" <leneahye@gmail.com>:

Thanks Thomas
Den 2. maj 2016 8.33 PM skrev "Thomas Parker Sr." <notifications@github.com

**Pull request closed without merging**
