### PR TITLE
Build collection lib along with the Android app

### PR DESCRIPTION
**Pull request by cco3**

### CODE REVIEW

**Comment by nondebug** [comment]
I'm getting an error with this change:

    12:11:06.105 [ERROR] [org.gradle.api.Project] Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
    Unknown source file : com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
    Unknown source file : 	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
    Unknown source file : 	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    Unknown source file : 	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
    Unknown source file : 	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
    Unknown source file : 	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
    Unknown source file : 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
    Unknown source file : 	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
    Unknown source file : 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
    Unknown source file : 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    Unknown source file : 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    Unknown source file : 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    Unknown source file : 	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
    Unknown source file : 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
    Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
    Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:246)
    Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:215)
    Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)
    Unknown source file : ...while parsing org/physical_web/collection/SimpleUrlDeviceJsonSerializer.class
    Unknown source file : 1 error; aborting

I ran `./gradlew check` and it looks like it encountered the exception during :app:preDexDebug.  I don't see the error if I build the libs or app separately.  Possibly environment-related?

**Comment by nondebug** [comment]
Looks like PATH was pulling in the wrong JDK.  Adding JDK 1.7 to the path fixed the build exception.

I'm still getting a build failure, this time because it's using the wrong "$project.rootDir" when evaluating checkstyle's suppressions.xml path for checkstyleIntegrationTest.  The path is:

    configProperties.checkstyleSuppressionsPath = file("$project.rootDir/config/checkstyle/suppressions.xml")

When we pull it in from the android app this resolves to `/android/PhysicalWeb/config/checkstyle/suppressions.xml` which doesn't exist (the app's config dir is `/android/PhysicalWeb/app/config`, but we actually want `/java/libs/config`)

This works but it's a bit of a hack:

    configProperties.checkstyleSuppressionsPath = file("$project.rootDir/../../java/libs/config/checkstyle/suppressions.xml")

**Comment by cco3** [comment]
Updated

**Comment by nondebug** [comment]
LGTM

**Pull request merged**
